import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Provider } from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Content Analaysis Tool",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
            <body className={inter.className + " min-h-screen flex flex-col"}>
                <Provider>
                    <NavBar session={session} />
                    {children}
                </Provider>
                <Toaster />
{/*                 <a href="https://github.com/ritik48/get_insight-frontend" target="_blank" className="absolute bottom-0 left-0 border-orange-300 flex items-center gap-1 m-3 border rounded-lg p-2">
                    <img src="/github.png" className="bg-white w-6" />
                    <span className="font-bold text-xs">Source Code</span>
                </a> */}
            </body>
        </html>
    );
}
